config/routes.rb
Rails.application.routes.draw do

  # root_path
  root to: 'public/homes#top'

  # devise関連
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #ゲストログイン用のルーティング
  devise_scope :customer do
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end


  #public_action
  scope module: :public do

    # customers_action
    get '/customers' => 'customers#show', as: 'customer'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'


    # foods_action
    resources :foods, only: [:index, :genre_search, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create]
      resource :prices, only: [:create, :update]
    end
    get '/foods/genre/:food_genre_id' => 'foods#genre', as: 'foods_genre'
    # get 'foods/search' => 'foods#search'

    # cutting_board_foods_action
    resources :cutting_board_foods
    delete '/cutting_board_foods' => 'cutting_board_foods#destroy_all', as: 'cutting_board_foods_destroy_all'
    get '/cutting_board_foods/genre/:genre_id' => 'cutting_board_foods#genre', as: 'cutting_board_foods_genre'


    # recipes_action
    resources :recipes, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    get 'recipe/search_tag' => 'recipes#search_tag'
    get '/recipe/search_favorite' => 'recipes#search_favorite'

    post 'recipe/:id/create_recipe_detail/' => 'recipes#create_recipe_detail', as: 'create_recipe_detail'
    patch 'recipe/:id/update_recipe_details/' => 'recipes#update_recipe_details', as: 'update_recipe_details'
    patch 'recipe/:id/update_recipes' => 'recipes#update_recipes', as: 'update_recipes'
    delete 'recipe/:id/update_recipe_detail/' => 'recipes#destroy_recipe_detail', as: 'destroy_recipe_detail'

    # meal_action
    resources :meals, only: [:show, :create, :update, :destroy]

    # diary_action
    resources :diaries, only: [:index, :show, :create, :update, :destroy]


  end


  # admin_action
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  ##admin_action
  namespace :admin do

    # foods
    resources :foods, only: [:index, :show, :edit, :update, :destroy]

    # comments
    resources :comments, only: [:index, :destroy]

    # customer
    resources :customers, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
  has_one_attached :image
  has_many :prices, dependent: :destroy
  has_many :cutting_board_foods, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :recipe_details, dependent: :destroy
  belongs_to :food_genre

  validates :name, presence: true
  validates :energy, presence: true
  validates :protein, presence: true
  validates :fat, presence: true
  validates :carb, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search(keyword)
    where('name LIKE?', "%#{keyword}%")
  end
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController
  before_action :authenticate_admin!
  before_action :make_instance, except: [:index]

  # 登録食材一覧
  def index
    @foods = Food.all
  end

  # 食材詳細
  def show
    # 食材についたコメント取得
    @comments = @food.comments
  end

  # 食材情報更新画面
  def edit
    @food_genres = FoodGenre.all
  end

  # 食材情報更新
  def update
    @food.update(food_params)
    redirect_to admin_food_path(params[:id])
  end

  # 食材削除
  def destroy
    @food.destroy
    redirect_to admin_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :energy, :protein, :fat, :carb, :salt_equivalent, :food_genre_id)
  end

  def make_instance
    @food = Food.find(params[:id])
  end
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/admin/foods/edit.html.erb
<h2 class="text-center">食材情報更新</h2>

<!--更新失敗時のエラー表示-->
<div>
  <% if @food.errors.any? %>
    <ul class="mx-auto">
      <%@food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>


<%= form_with model: @food, url: admin_food_path, method: :patch do |f| %>
  <table class="table-sm mx-auto">
    <tbody>
      <tr>
        <td style="width: 120px"><%= f.label :name, "名前(必須)" %></td>
        <td class=""><%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control-sm mx-2' %></td>
      </tr>

      <tr>
        <td><%= f.label :food_genre_id, "ジャンル(必須)" %></td>
        <td><%= f.collection_select(:food_genre_id, @food_genres, :id, :name, {}, {class: 'form-control-sm mx-2'}) %></td>
      </tr>

      <tr>
        <td><%= f.label :energy, "カロリー(必須)" %></td>
        <td><%= f.text_field :energy, autofocus: true, autocomplete: "energy", class: 'form-control-sm mx-2' %>kcal</td>
      </tr>

      <tr>
        <td><%= f.label :protein, "たんぱく質" %></td>
        <td><%= f.text_field :protein, autofocus: true, autocomplete: "protein", class: 'form-control-sm mx-2' %>g</td>
      </tr>

      <tr>
        <td><%= f.label :fat, "脂質" %></td>
        <td><%= f.text_field :fat, autofocus: true, autocomplete: "fat", class: 'form-control-sm mx-2' %>g</td>
      </tr>

      <tr>
        <td><%= f.label :carb, "炭水化物" %></td>
        <td><%= f.text_field :carb, autofocus: true, autocomplete: "carb", class: 'form-control-sm mx-2' %>g</td>
      </tr>

      <tr>
        <td><%= f.label :salt_equivalent, "塩分" %></td>
        <td><%= f.text_field :salt_equivalent, autofocus: true, autocomplete: "salt_equivalent", class: 'form-control-sm mx-2' %>g</td>
      </tr>

      <tr>
        <td><%= f.label :image, "写真" %></td>
        <td><%= f.file_field :image, accept: "image/*", class:"w-100"  %></td>
      </tr>

      <tr>
        <td class="text-center" colspan="2"><%= f.submit "登録", class: "btn btn-success" %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/admin/foods/index.html.erb
<h2 class="text-center mb-2">食材一覧</h2>
  <table class="table table-sm table-bordered mx-auto">
    <tbody>
      <tr class="text-center">
        <th>食材名</th>

        <th>分類</th>

        <th>エネルギー</th>

        <th>たんぱく質</th>

        <th>脂質</th>

        <th>炭水化物</th>

        <th>塩分</th>

        <th style="width: 170px;"></th>
      </tr>

      <% @foods.each do |food| %>
        <tr>

          <!--食材詳細へのリンク-->
          <td class="text-center">
            <%= link_to admin_food_path(food.id) do %>
              <%= food.name %>
            <% end %>
          </td>

          <td><%= food.food_genre.name %></td>

          <td class="text-right"><%= food.energy %> kcal</td>

          <td class="text-right"><%= food.protein %> g</td>

          <td class="text-right"><%= food.fat %> g</td>

          <td class="text-right"><%= food.carb %> g</td>

          <td class="text-right"><%= food.salt_equivalent %> g</td>

          <!--食材更新・削除-->
          <td class="text-center">
            <%= link_to "更新", edit_admin_food_path(food.id), class: 'btn btn-success px-3 mx-1' %>
            <%= link_to "削除", admin_food_path(food.id), method: :delete, class: 'btn btn-danger px-3 mx-1' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/foods/show.html.erb
<h2 class="text-center mb-2"><%= @food.name %></h2>

<div class="row">

  <!--写真表示-->
  <div class="col-6">
    <%= image_tag @food.get_image(540,500) %>
  </div>

  <!--食材データ表示-->
  <div class="col-6">
    <table class="table table-sm table-bordered mx-auto" style="width: 250px;">
      <tr class="text-center">
        <th colspan="3">栄養素 / 100gあたり</th>
      </tr>

      <tr>
        <th class="text-center" style="width: 120px;">エネルギー</th>
        <td class="text-right" style="width: 80px;"><%= @food.energy %></td>
        <td style="width: 25px;">kcal</td>
      </tr>

      <tr>
        <th class="text-center">たんぱく質</th>
        <td class="text-right"><%= @food.protein %></td>
        <td>g</td>
      </tr>

      <tr>
        <th class="text-center">脂質</th>
        <td class="text-right"><%= @food.fat %></td>
        <td>g</td>
      </tr>

      <tr>
        <th class="text-center">炭水化物</th>
        <td class="text-right"><%= @food.carb %></td>
        <td>g</td>
      </tr>

      <tr>
        <th class="text-center">食塩相当量</th>
        <td class="text-right"><%= @food.salt_equivalent %></td>
        <td>g</td>
      </tr>

      <tr class="text-center">
        <td colspan="3">
          <%= link_to "更新", edit_admin_food_path(params[:id]), class: 'btn btn-success px-3' %>
        </td>
      </tr>
    </table>

    <div>

    </div>
  </div>
</div>

<!--コメント一覧-->
<div>
  <table class="table table-sm table-bordered mx-auto text-center">
    <tbody>
      <tr>
        <th>投稿者</th>

        <th>コメントジャンル</th>

        <th>コメント</th>

        <th></th>
      </tr>

      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.customer.name %></td>

          <td><%= comment.comment_genre.name %></td>

          <td><%= comment.comment %></td>

          <!--コメント削除-->
          <td>
            <%= link_to "削除", admin_comment_path(comment.id), method: :delete, class: 'btn btn-danger px-3' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>