config/routes.rb
Rails.application.routes.draw do

  # root_path
  root to: 'public/homes#top'

  # devise関連
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #ゲストログイン用のルーティング
  devise_scope :customer do
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end


  #public_action
  scope module: :public do

    # customers_action
    get '/customers' => 'customers#show', as: 'customer'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'


    # foods_action
    resources :foods, only: [:index, :genre_search, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create]
      resource :prices, only: [:create, :update]
    end
    get '/foods/genre/:food_genre_id' => 'foods#genre', as: 'foods_genre'
    # get 'foods/search' => 'foods#search'

    # cutting_board_foods_action
    resources :cutting_board_foods
    delete '/cutting_board_foods' => 'cutting_board_foods#destroy_all', as: 'cutting_board_foods_destroy_all'
    get '/cutting_board_foods/genre/:genre_id' => 'cutting_board_foods#genre', as: 'cutting_board_foods_genre'


    # recipes_action
    resources :recipes, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    get 'recipe/search_tag' => 'recipes#search_tag'
    get '/recipe/search_favorite' => 'recipes#search_favorite'

    post 'recipe/:id/create_recipe_detail/' => 'recipes#create_recipe_detail', as: 'create_recipe_detail'
    patch 'recipe/:id/update_recipe_details/' => 'recipes#update_recipe_details', as: 'update_recipe_details'
    patch 'recipe/:id/update_recipes' => 'recipes#update_recipes', as: 'update_recipes'
    delete 'recipe/:id/update_recipe_detail/' => 'recipes#destroy_recipe_detail', as: 'destroy_recipe_detail'

    # meal_action
    resources :meals, only: [:show, :create, :update, :destroy]

    # diary_action
    resources :diaries, only: [:index, :show, :create, :update, :destroy]


  end


  # admin_action
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  ##admin_action
  namespace :admin do

    # foods
    resources :foods, only: [:index, :show, :edit, :update, :destroy]

    # comments
    resources :comments, only: [:index, :destroy]

    # customer
    resources :customers, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meals, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :prices, dependent: :destroy
  has_many :cutting_board_foods, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.guest
    # ゲストユーザーの取り出しor作成
    find_or_create_by!(email: 'aaa@aaa.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.password_confirmation = customer.password
      customer.name = 'ゲスト'
    end
  end

  def favorited?(recipe_id)
    favorites.exists?(recipe_id:)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to admin_customers_path
  end

  def favorites
    favorites = Favorite.where(customer_id: current_customer.id).pluck(:recipe_id)
    @favorite_foods = Recipe.find(favorites)
  end
end

app/views/admin/customers/index.html.erb
<h2 class="text-center mb-2">ユーザー一覧</h3>
<table class="table table-sm table-bordered mx-auto" style="width: 440px;">
  <tbody>
    <tr class="text-center">
      <th style="width: 150px;">ユーザー</th>
      <th style="width: 110px;">レシピ投稿数</th>
      <th style="width: 100px;">コメント数</th>
      <th style="width: 80px;"></th>
    </tr>

    <!--ユーザー一覧-->
    <% @customers.each do |customer| %>
      <tr>

        <!--ユーザー詳細(コメント一覧)へのリンク-->
        <td class="text-center">
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.name %>
          <% end %>
        </td>

        <td><%= customer.recipes.count %></td>

        <td><%= customer.comments.count %></td>

        <!--ユーザー削除-->
        <td class="text-center">
          <%= link_to "削除", admin_customer_path(customer.id), method: :delete, class: 'btn btn-danger px-3' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/customers/show.html.erb
<h2 class="text-center mb-2"><%= @customer.name %></h2>

<!--コメント一覧-->
<table class="table table-sm table-bordered">
  <tbody>
    <tr class="text-center">
      <th colspan="3">コメント一覧</th>
    </tr>

    <tr class="text-center">
      <th>コメントジャンル</th>

      <th>コメント</th>

      <th></th>
    </tr>

    <% @customer.comments.each do |comment| %>
      <tr>
        <td>
          <%= comment.comment_genre.name %>
        </td>

        <td>
          <%= comment.comment %>
        </td>

        <td>
          <%= link_to "削除", admin_comment_path(comment.id), method: :delete, class: 'btn btn-danger px-3' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!--ユーザー削除-->
<div class="text-center">
  <%= link_to "このユーザーを削除する", admin_customer_path(params[:id]), method: :delete, class: 'btn btn-danger px-3' %>
</div>