config/routes.rb
Rails.application.routes.draw do

  # root_path
  root to: 'public/homes#top'

  # devise関連
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  #ゲストログイン用のルーティング
  devise_scope :customer do
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end


  #public_action
  scope module: :public do

    # customers_action
    get '/customers' => 'customers#show', as: 'customer'
    get '/customers/edit' => 'customers#edit'
    patch '/customers' => 'customers#update'


    # foods_action
    resources :foods, only: [:index, :genre_search, :new, :create, :show, :edit, :update] do
      resources :comments, only: [:create]
      resource :prices, only: [:create, :update]
    end
    get '/foods/genre/:food_genre_id' => 'foods#genre', as: 'foods_genre'
    # get 'foods/search' => 'foods#search'

    # cutting_board_foods_action
    resources :cutting_board_foods
    delete '/cutting_board_foods' => 'cutting_board_foods#destroy_all', as: 'cutting_board_foods_destroy_all'
    get '/cutting_board_foods/genre/:genre_id' => 'cutting_board_foods#genre', as: 'cutting_board_foods_genre'


    # recipes_action
    resources :recipes, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    get 'recipe/search_tag' => 'recipes#search_tag'
    get '/recipe/search_favorite' => 'recipes#search_favorite'

    post 'recipe/:id/create_recipe_detail/' => 'recipes#create_recipe_detail', as: 'create_recipe_detail'
    patch 'recipe/:id/update_recipe_details/' => 'recipes#update_recipe_details', as: 'update_recipe_details'
    patch 'recipe/:id/update_recipes' => 'recipes#update_recipes', as: 'update_recipes'
    delete 'recipe/:id/update_recipe_detail/' => 'recipes#destroy_recipe_detail', as: 'destroy_recipe_detail'

    # meal_action
    resources :meals, only: [:show, :create, :update, :destroy]

    # diary_action
    resources :diaries, only: [:index, :show, :create, :update, :destroy]


  end


  # admin_action
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  ##admin_action
  namespace :admin do

    # foods
    resources :foods, only: [:index, :show, :edit, :update, :destroy]

    # comments
    resources :comments, only: [:index, :destroy]

    # customer
    resources :customers, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nutrition_graph.html.erb
          <canvas id="myChart"></canvas>
         
          <script>
            var ctx = document.getElementById('myChart');
            var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                labels: [
                  'カロリー',
                  'たんぱく質',
                  '脂質',
                  '炭水化物',
                  '塩分'
                ],
                datasets: [{
                  label: '<%= date %>の摂取量 / 一日の必要',
                  data: [
                    <%= chart_energy %>,
                    <%= chart_protein %>,
                    <%= chart_fat %>,
                    <%= chart_carb %>,
                    <%= chart_salt_equivalent %>
                  ],
                  backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)'
                  ],
                  clip: {left: 0, top: false, right: -2, bottom: 0},
                  borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)'
                  ],
                    borderWidth: 1
                }]
              },
              options: {
                scales: {
                  x: {
                    id: 'nutrition'
                  },
                  y: {
                    id: 'ratio',
                    beginAtZero: true,
                    suggestedMax: 1
                  }
                },


                annotation: {
                  annotations: [{
                    type: 'line', // 線分を指定
                    drawTime: 'afterDatasetsDraw',
                    id: 'a-line-1', // 線のid名を指定（他の線と区別するため）
                    mode: 'horizontal', // 水平を指定
                    scaleID: 'ratio', // 基準とする軸のid名
                    value: 1, // 引きたい線の数値（始点）
                    endValue: 1, // 引きたい線の数値（終点）
                    borderColor: 'red', // 線の色
                    borderWidth: 3, // 線の幅（太さ）
                    borderDash: [2, 2],
                    borderDashOffset: 1,
                    label: { // ラベルの設定
                      backgroundColor: 'rgba(255,255,255,0.8)',
                      bordercolor: 'rgba(200,60,60,0.8)',
                      borderwidth: 2,
                      fontSize: 10,
                      fontStyle: 'bold',
                      fontColor: 'rgba(200,60,60,0.8)',
                      xPadding: 10,
                      yPadding: 10,
                      cornerRadius: 3,
                      position: 'left',
                      xAdjust: 0,
                      yAdjust: 0,
                      enabled: true,
                      content: '必要値'
                    }
                  }]
                }
              }
            });
          </script>

app/views/layouts/_search.html.erb
<div class="input-group  mx-auto" style="max-width: 810px">
  <%= f.text_field :keyword, value: keyword, class: "form-control search-control", placeholder: "キーワードを入力" %>
  <span class="input-group-btn input-group-append">
    <%= button_tag type: "submit", class: "btn btn-secondary search-btn" do %>
      <i class="fas fa-search"></i> 検索</submit>
    <% end %>
  </span>
</div>

app/views/layouts/_weight_graph.html.erb
<canvas id="myChart1"></canvas>
          <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
          <script>
            var ctx = document.getElementById('myChart1');
            var myChart = new Chart(ctx, {
              type: 'line',
              data: {
                labels: [
                  <% i = 0 %>
                  <%= while i < (days - 1) do %>
                    "<%= date.to_date.ago((days - 1 -i).days).strftime('%m/%d').to_s %>",
                    <% i += 1 %>
                  <% end %>
                  "<%= date.to_date.strftime('%m/%d').to_s %>"
                ],
                datasets: [{
                  label: '体重の記録',
                  data: [
                    <% i = 0 %>
                    <%= while i < days do %>
                      <%= body_weights[i] == 0 ? nil : body_weights[i].to_f %>,
                      <% i += 1 %>
                    <% end %>
                  ],
                }]
              },
              options: {
                scales: {
                  x: {
                    id: 'nutrition'
                  },
                  y: {
                    id: 'ratio',

                  }
                },
              }
            });
          </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JisuiNikki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://kit.fontawesome.com/1497b7da49.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Klee+One&display=swap" rel="stylesheet">
  </head>

  <body>

    <!--header-->
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark w-100">
        <div class="container">

          <!--アプリロゴ(ホームリンク)-->
          <a class="navbar-brand p-5px" href="/">みんなの自炊日記</a>

          <!--メニュー(ハンバーガー)-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>

          <!--メニュー(コンテンツ) => ログイン状態で変化-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <!--管理者ログイン時-->
              <% if admin_signed_in? %>

                <!--食材一覧-->
                <li class="nav-link px-3">
                  <%= link_to admin_foods_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-search"></i>&nbsp;食材一覧&nbsp;<i class="far fa-lightbulb"></i>
                  <% end %>
                </li>

                <!--コメント一覧-->
                <li class="nav-link px-3">
                  <%= link_to admin_comments_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-search"></i>&nbsp;コメント一覧&nbsp;<i class="far fa-lightbulb"></i>
                  <% end %>
                </li>

                <!--ユーザー一覧-->
                <li class="nav-link px-3">
                  <%= link_to admin_customers_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-search"></i>&nbsp;ユーザー一覧&nbsp;<i class="far fa-lightbulb"></i>
                  <% end %>
                </li>

                <!--ログアウト-->
                <li class="nav-link px-3">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-sign-out-alt"></i>&nbsp;ログアウト
                  <% end %>
                </li>

              <!--ユーザーログイン時-->
              <% elsif customer_signed_in? %>

                <!--マイページ-->
                <li class="nav-link px-3">
                  <%= link_to customer_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-calendar-alt"></i>&nbsp;マイページ
                  <% end %>
                </li>

                <!--食材一覧-->
                <li class="nav-link px-3">
                  <%= link_to foods_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>

                    <i class="fas fa-drumstick-bite"></i>
                    &nbsp;食材&nbsp;

                  <% end %>
                </li>

                <!--食材登録-->
                <li class="nav-link px-3">
                  <%= link_to new_food_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-search"></i>&nbsp;食材登録&nbsp;
                  <% end %>
                </li>

                <!--レシピ一覧-->
                <li class="nav-link px-3">
                  <%= link_to recipes_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-utensils"></i>&nbsp;レシピ
                  <% end %>
                </li>

                <!--まな板へ-->
                <li class="nav-link px-3">
                  <%= link_to cutting_board_foods_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-utensils"></i>&nbsp;レシピ作成
                  <% end %>
                </li>

                <!--ログアウト-->
                <li class="nav-link px-3">
                  <%= link_to destroy_customer_session_path, method: :delete, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-sign-out-alt"></i>&nbsp;ログアウト
                  <% end %>
                </li>



              <!--非ログイン時-->
              <% else %>

                <!--ゲストログイン-->
                <li class="nav-link p-8px">
                  <%= link_to guest_sign_in_path, method: :post, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-home"></i>&nbsp;ゲストログイン(閲覧用)
                  <% end %>
                </li>

                <!--会員登録-->
                <li class="nav-link p-8px">
                  <%= link_to new_customer_registration_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-home"></i>&nbsp;会員登録
                  <% end %>
                </li>

                <!--ログイン-->
                <li class="nav-link p-8px">
                  <%= link_to new_customer_session_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-home"></i>&nbsp;ログイン
                  <% end %>
                </li>

                <!--管理者ログイン-->
                <li class="nav-link p-8px">
                  <%= link_to new_admin_session_path, class: 'd-flex align-items-center text-light text-decoration-none' do %>
                    <i class="fas fa-home"></i>&nbsp;管理者ログイン
                  <% end %>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container py-3">
      <%= yield %>
    </div>

    <footer></footer>
  </body>
</html>